### ISSUE TITLE
consider ways of retrieving git status without the entire git history

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#157]
#155 added back the entire git history to the Docker image to enable us to capture the git status

It would be advantageous to be able to get the git status without having to copy in the entire git history (and possibly not needing `git`, just parsing specific files). Some ideas towards this we're discussed in #138 

Specifically, we can probably get the current git hash from just the files `.git/HEAD` (to get the current branch name) and `.git/refs/heads/{CURRENT-BRANCH-NAME}`.

git tags we don't yet have a solution for

git status should be possible with a "depth=1" clone, though it may end up confusing since we're purposefully not copying in all files (maybe we should look towards checking the git status of only specific files we want to check?)

**Comment by AlexAxthelm** [comment]
@cjyetman worth noting that the `actions/checkout` action we're using as part of the [build workflow](https://github.com/RMI-PACTA/actions/blob/27557134b3d327b36644761be02169d07466ea51/.github/workflows/docker-build-multiarch.yml#L69-L72) defaults to using `depth=1`

**Comment by cjyetman** [comment]
confirmed that the current situation makes `git status` quite noisy, but additionally so because the repo is being copied into the root directory of the Docker image rather than a subdirectory (another solid reason to optimally find a way to check the git status of only specific files)...

```yaml
  "git": {
    "local_git_tag": "no git tags found",
    "local_git_hash": "ee97f2649fbb47188fc64509a788ee073f93653b",
    "local_git_status": [
      {
        "status": "",
        "filename": "D .dockerignore"
      },
      {
        "status": "",
        "filename": "D .github/CODEOWNERS"
      },
      {
        "status": "",
        "filename": "D .github/workflows/add-prs-and-issues-to-project.yml"
      },
      {
        "status": "",
        "filename": "D .gitignore"
      },
      {
        "status": "",
        "filename": "D Dockerfile"
      },
      {
        "status": "",
        "filename": "M config.yml"
      },
      {
        "status": "",
        "filename": "D docker-compose.yml"
      },
      {
        "status": "",
        "filename": "D workflow.data.preparation.Rproj"
      },
      {
        "status": "??",
        "filename": ".dockerenv"
      },
      {
        "status": "??",
        "filename": ".env"
      },
      {
        "status": "??",
        "filename": "bin"
      },
      {
        "status": "??",
        "filename": "dev/"
      },
      {
        "status": "??",
        "filename": "etc/"
      },
      {
        "status": "??",
        "filename": "home/"
      },
      {
        "status": "??",
        "filename": "init"
      },
      {
        "status": "??",
        "filename": "inputs/"
      },
      {
        "status": "??",
        "filename": "lib"
      },
      {
        "status": "??",
        "filename": "lib32"
      },
      {
        "status": "??",
        "filename": "lib64"
      },
      {
        "status": "??",
        "filename": "libexec/"
      },
      {
        "status": "??",
        "filename": "libx32"
      },
      {
        "status": "??",
        "filename": "opt/"
      },
      {
        "status": "??",
        "filename": "outputs/"
      },
      {
        "status": "??",
        "filename": "proc/"
      },
      {
        "status": "??",
        "filename": "rocker_scripts/"
      },
      {
        "status": "??",
        "filename": "root/"
      },
      {
        "status": "??",
        "filename": "run/"
      },
      {
        "status": "??",
        "filename": "sbin"
      },
      {
        "status": "??",
        "filename": "sys/"
      },
      {
        "status": "??",
        "filename": "tmp/"
      },
      {
        "status": "??",
        "filename": "usr/"
      },
      {
        "status": "??",
        "filename": "var/"
      }
    ]
  },
```
