### ISSUE TITLE
remove FactSet database code

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.data.preparation#72]
If the FactSet database is dead for good (@AlexAxthelm?), we should remove all the code and parameters related to that and effectively set `update_factset: FALSE` all the time
https://github.com/RMI-PACTA/workflow.data.preparation/blob/3908094ba85dbae289e5c888612359fd23f5bedc/config.yml#L9

This would likely lead to significant simplification of the process. We should probably also deprecate and remove the relevant functions in pacta.data.preparation.

**Comment by AlexAxthelm** [comment]
I think we can remove that key entirely, and replace it with something like 
```yml
default:
  ...
  factset_data_path: /mnt/inputs/factset

2023Q4:
  ...
  factset_data_path: /mnt/factset-extracted/factset-pacta_timestamp-20231231T000000Z_pulled-20240103T112256Z
```
